### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by neomilium**
Some of the recent changes I made broke the tests.

This PR contains a rewritten output processing method in order to work with any tested command and provides a better way to catch errors using CLI.

### CODE REVIEW

**Comment by neomilium** [comment]
@sepulworld Could you tag and release a new gem, please?

**Comment by sepulworld** [comment]
Will do tonight 

On March 5, 2022, fejta-bot ***@***.***> wrote:
> @sepulworld <https://github.com/sepulworld> Could you tag and release
> a new gem, please?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/sepulworld/aptly_cli/pull/161#issuecomment-
1059851450>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAEDMO2MB6IG6K3KFOPN373U6PV3NANCNFSM5P732UWA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by sepulworld** [comment]
ok released https://github.com/sepulworld/aptly_cli/runs/5436079002?check_suite_focus=true

0.6.0

**Comment by neomilium** [comment]
Great, Thanks!

**Pull request merged**
